import json
import os
from datetime import datetime, timezone

import joblib
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score
from xgboost import XGBClassifier

from data_preprocessing import preprocess_pipeline


os.makedirs("models", exist_ok=True)
os.makedirs("results", exist_ok=True)

print("Loading and preprocessing data...")
X_train, X_test, y_train, y_test = preprocess_pipeline()

models = {
    "Logistic_Regression": LogisticRegression(max_iter=1000),
    "Random_Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric="logloss"),
    "Gradient_Boosting": GradientBoostingClassifier(),
}

results = []
for name, model in models.items():
    print(f"Training {name}...")
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_prob)
    results.append({"Model": name, "Accuracy": acc, "ROC-AUC": roc})

    joblib.dump(model, f"models/{name.lower()}.pkl")

results_df = pd.DataFrame(results)
results_df.to_csv("results/model_comparison.csv", index=False)
print(results_df)

best_model_row = results_df.sort_values(by="ROC-AUC", ascending=False).iloc[0]
best_model_name = best_model_row["Model"]
best_estimator = models[best_model_name]
joblib.dump(best_estimator, "models/best_model.pkl")
print(f"Best model: {best_model_name}")

feature_schema = ["age", "job", "housing", "saving", "checking", "credit", "duration", "purpose", "sex", "other"]
metadata = {
    "model_name": f"{best_model_name}.pkl",
    "model_version": datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S"),
    "trained_at_utc": datetime.now(timezone.utc).isoformat(),
    "feature_schema": feature_schema,
    "notes": "Generated by train_models.py",
}
with open("models/model_metadata.json", "w", encoding="utf-8") as fh:
    json.dump(metadata, fh, indent=2)

calibrator = CalibratedClassifierCV(best_estimator, method="sigmoid", cv="prefit")
calibrator.fit(X_train, y_train)
joblib.dump(calibrator, "models/risk_calibrator.pkl")
print("Saved best model, metadata, and calibrator.")
